[package]
name = "rlox1"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["environment", "models"]

[dependencies]
environment = { path = "./environment" }
models = { path = "./models" }
lazy_static = "1.5.0"
rstest = "0.22.0"
thiserror = "1.0.63"
